name: Build and Publish Docker Image

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches: [ main ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: winglang
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t wing-action .

          # For main branch, tag it as 'main'
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag wing-action ghcr.io/winglang/wing-github-action:main
            docker push ghcr.io/winglang/wing-github-action:main
          fi

          # For new tags, tag the docker image with the same tag
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            docker tag wing-action ghcr.io/winglang/wing-github-action:$TAG
            docker push ghcr.io/winglang/wing-github-action:$TAG
          fi
